# Generated by Django 5.0.10 on 2026-10-09 06:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('meals_distributed', models.BigIntegerField(default=0)),
                ('kilograms_rescued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('waste_avoided_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('donors_engaged', models.PositiveIntegerField(default=0)),
                ('volunteers_engaged', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(blank=True, limit_choices_to={'role': 'NGO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_impact_metric',
                'unique_together': {('report_date', 'ngo')},
            },
        ),
    ]
