# Generated by Django 5.0.10 on 2026-10-09 06:45

import apps.accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0002_fooddonation_accepted_ngo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking_beneficiary',
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACCEPTED', 'Accepted by volunteer'), ('IN_TRANSIT', 'In transit'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, limit_choices_to={'role': 'VOLUNTEER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='tracking.beneficiary')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='donations.fooddonation')),
                ('ngo', models.ForeignKey(blank=True, limit_choices_to={'role': 'NGO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracking_pickup',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(default='GOOD', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('proof_file', models.FileField(blank=True, null=True, storage=apps.accounts.storage.PrivateUploadStorage(), upload_to='delivery-proofs/')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='tracking.pickup')),
            ],
            options={
                'db_table': 'tracking_delivery_log',
            },
        ),
        migrations.CreateModel(
            name='PickupStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled'), ('ACCEPTED', 'Accepted by volunteer'), ('IN_TRANSIT', 'In transit'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='', max_length=20)),
                ('new_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACCEPTED', 'Accepted by volunteer'), ('IN_TRANSIT', 'In transit'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_status_changes', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracking.pickup')),
            ],
            options={
                'db_table': 'tracking_pickup_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pickup',
            constraint=models.CheckConstraint(check=models.Q(('pickup_window_end__gt', models.F('pickup_window_start'))), name='pickup_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='pickup',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('donation',), name='unique_active_pickup_per_donation'),
        ),
        migrations.AddConstraint(
            model_name='deliverylog',
            constraint=models.UniqueConstraint(fields=('pickup',), name='unique_delivery_log_per_pickup'),
        ),
    ]
