# Generated by Django 5.0.10 on 2026-10-09 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_accepted_ngo_and_more'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(condition=models.Q(('donation__isnull', False)), fields=('user', 'donation'), name='unique_feedback_per_user_donation'),
        ),
    ]
