# Generated by Django 5.0.10 on 2026-10-09 06:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_audits', to='donations.fooddonation')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_audits', to='donations.donationrequest')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_match_audit',
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='donations.fooddonation')),
                ('matched_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_candidates', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='donations.donationrequest')),
            ],
            options={
                'db_table': 'matching_match_candidate',
            },
        ),
        migrations.CreateModel(
            name='NGOMatchingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_demand_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reliability_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_categories', models.ManyToManyField(blank=True, related_name='matching_ngos', to='donations.foodcategory')),
                ('ngo', models.OneToOneField(limit_choices_to={'role': 'NGO'}, on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_ngo_profile',
            },
        ),
        migrations.CreateModel(
            name='NGORecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('factor_scores', models.JSONField(default=dict)),
                ('factor_weights', models.JSONField(default=dict)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('explanation', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('SUPERSEDED', 'Superseded')], default='RECOMMENDED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_recommendations', to='donations.fooddonation')),
                ('ngo', models.ForeignKey(limit_choices_to={'role': 'NGO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_ngo_recommendation',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.UniqueConstraint(fields=('donation', 'request'), name='unique_match_candidate_for_donation_request'),
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.CheckConstraint(check=models.Q(('compatibility_score__gte', 0)), name='match_candidate_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ngomatchingprofile',
            constraint=models.CheckConstraint(check=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='ngo_match_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ngomatchingprofile',
            constraint=models.CheckConstraint(check=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='ngo_match_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ngomatchingprofile',
            constraint=models.CheckConstraint(check=models.Q(('current_demand_score__lte', 100)), name='ngo_match_demand_score_range'),
        ),
        migrations.AddConstraint(
            model_name='ngomatchingprofile',
            constraint=models.CheckConstraint(check=models.Q(('reliability_score__lte', 100)), name='ngo_match_reliability_score_range'),
        ),
        migrations.AddConstraint(
            model_name='ngorecommendation',
            constraint=models.CheckConstraint(check=models.Q(('match_score__gte', 0), ('match_score__lte', 100)), name='ngo_match_score_range'),
        ),
        migrations.AddConstraint(
            model_name='ngorecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['RECOMMENDED', 'ACCEPTED'])), fields=('donation', 'ngo'), name='unique_active_ngo_match_per_donation'),
        ),
    ]
