# Generated by Django 5.0.10 on 2026-10-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.TextField()),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('deduplication_key', models.CharField(max_length=64)),
                ('detection_method', models.CharField(default='RULE_BASED', max_length=40)),
                ('rule_version', models.CharField(default='fraud-rules-v1', max_length=40)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('review_outcome', models.CharField(blank=True, choices=[('NO_ACTION', 'No action required'), ('FALSE_POSITIVE', 'False positive'), ('POLICY_VIOLATION', 'Policy violation'), ('ESCALATED', 'Escalated for further review')], default='', max_length=30)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='donations.fooddonation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_detection_fraud_alert',
                'ordering': ['-risk_score', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.BigIntegerField(default=0)),
                ('action', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_detection_audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='fraud_detec_entity__aafd07_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fraudalert',
            constraint=models.CheckConstraint(check=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='fraud_alert_score_range'),
        ),
        migrations.AddConstraint(
            model_name='fraudalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'REVIEWING'])), fields=('deduplication_key',), name='unique_unresolved_fraud_alert_issue'),
        ),
    ]
