# Generated by Django 5.0.10 on 2026-10-09 04:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donations_food_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('preparation_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.DateTimeField()),
                ('storage_condition', models.CharField(choices=[('AMBIENT', 'Ambient'), ('REFRIGERATED', 'Refrigerated'), ('FROZEN', 'Frozen'), ('ROOM_TEMPERATURE', 'Room temperature')], default='AMBIENT', max_length=30)),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup scheduled'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='AVAILABLE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.foodcategory')),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'DONOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations_food_donation',
            },
        ),
        migrations.CreateModel(
            name='DonationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup scheduled'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='', max_length=32)),
                ('new_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('PICKUP_SCHEDULED', 'Pickup scheduled'), ('PICKED_UP', 'Picked up'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='donations.fooddonation')),
            ],
            options={
                'db_table': 'donations_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(limit_choices_to={'role': 'NGO'}, on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.fooddonation')),
            ],
            options={
                'db_table': 'donations_donation_request',
            },
        ),
        migrations.CreateModel(
            name='DonationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.donationrequest')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donations.fooddonation')),
            ],
            options={
                'db_table': 'donations_donation_match',
            },
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['status', 'expiry_time'], name='donations_f_status_3257ad_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['donor', 'status'], name='donations_f_donor_i_a0f848_idx'),
        ),
        migrations.AddConstraint(
            model_name='fooddonation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='food_donation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='fooddonation',
            constraint=models.CheckConstraint(check=models.Q(('food_name', ''), _negated=True), name='food_donation_name_required'),
        ),
        migrations.AddConstraint(
            model_name='fooddonation',
            constraint=models.CheckConstraint(check=models.Q(('pickup_address', ''), _negated=True), name='food_donation_pickup_address_required'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status', 'created_at'], name='donations_d_status_9d296a_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationrequest',
            constraint=models.CheckConstraint(check=models.Q(('requested_quantity__gt', 0)), name='donation_request_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='donationrequest',
            constraint=models.UniqueConstraint(fields=('donation', 'ngo'), name='unique_request_per_donation_and_ngo'),
        ),
        migrations.AddConstraint(
            model_name='donationmatch',
            constraint=models.UniqueConstraint(fields=('donation', 'request'), name='unique_donation_match_per_request'),
        ),
        migrations.AddConstraint(
            model_name='donationmatch',
            constraint=models.CheckConstraint(check=models.Q(('match_score__gte', 0)), name='match_score_non_negative'),
        ),
    ]
