# Generated by Django 5.0.10 on 2026-10-09 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='accepted_ngo',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'NGO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='donationmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('donation',), name='unique_accepted_donation_match'),
        ),
    ]
